/**
 * VND Enhanced — License Client
 *
 * Handles Patreon OAuth, JWT token management, device fingerprinting,
 * periodic heartbeat, and feature gating.
 *
 * All sensitive operations (token issuance, subscription verification)
 * happen on the server. This file is the client-side coordinator only.
 */

const MODULE_ID  = 'vnd-enhanced';
const API_BASE   = 'https://vnd-license.gmredvelvet.workers.dev';

// HMAC-SHA256 response signing key (public — embedded here to verify server responses)
// Generated by: node backend/scripts/generate-keys.js
// This is NOT a secret — it only allows verifying that responses came from YOUR server.
const RESPONSE_SIGN_SECRET = 'hYt9J4j9GnF-cZN54x4ClB1odAFM71SvZAyOUxlgZrY';

// ── Storage keys (localStorage) ───────────────────────────────────────────────
const SK = {
  accessToken:    `${MODULE_ID}:at`,
  refreshToken:   `${MODULE_ID}:rt`,
  tokenExpiry:    `${MODULE_ID}:exp`,
  installationId: `${MODULE_ID}:iid`,
  tier:           `${MODULE_ID}:tier`,
  features:       `${MODULE_ID}:features`,
};

// ── VndLicenseClient ──────────────────────────────────────────────────────────

export class VndLicenseClient {
  static #instance = null;

  #accessToken      = null;
  #refreshToken     = null;
  #tokenExpiry      = 0;
  #installationId   = null;
  #fingerprint      = null;
  #features         = [];
  #tier             = 'none';
  #heartbeatTimer   = null;
  #lastHeartbeat    = 0;
  #gracePeriodMs    = 5 * 60 * 1000;   // 5 minutes without valid heartbeat before degraded mode
  #degraded         = false;

  static get instance() {
    if (!this.#instance) this.#instance = new VndLicenseClient();
    return this.#instance;
  }

  // ── Initialization ──────────────────────────────────────────────────────────

  async initialize() {
    this.#installationId = this.#getOrCreateInstallationId();
    this.#fingerprint    = await this.#computeFingerprint();
    this.#loadStoredTokens();

    // If we have a valid (non-expired) access token, we're good
    if (this.#accessToken && this.#isAccessTokenValid()) {
      this.#tier     = this.#parseTierFromToken();
      this.#features = this.#parseFeaturesFromToken();
      this.#startHeartbeat();
      return true;
    }

    // Try refresh token
    if (this.#refreshToken) {
      try {
        await this.#doRefresh();
        this.#startHeartbeat();
        return true;
      } catch {
        this.#clearStoredTokens();
      }
    }

    return false; // Needs re-authentication
  }

  // ── Feature gate ───────────────────────────────────────────────────────────

  hasFeature(featureName) {
    if (this.#degraded) return false;
    if (!this.#accessToken || !this.#isAccessTokenValid()) return false;
    return this.#features.includes(featureName);
  }

  get tier() { return this.#tier; }
  get isLicensed() { return this.#tier !== 'none' && !this.#degraded; }

  // ── OAuth flow ─────────────────────────────────────────────────────────────

  async startOAuth() {
    // Open auth URL in a popup
    const { url } = await this.#apiCall('/oauth/start', null, 'GET');
    const popup   = window.open(url, 'vnd-patreon-auth', 'width=600,height=700,popup=yes');

    return new Promise((resolve, reject) => {
      const handler = async (event) => {
        if (event.data?.type !== 'vnd-auth-code') return;
        window.removeEventListener('message', handler);
        popup?.close();
        try {
          await this.activateWithCode(event.data.authCode);
          resolve(true);
        } catch (e) {
          reject(e);
        }
      };
      window.addEventListener('message', handler);

      // Fallback: user closes popup without postMessage
      const interval = setInterval(() => {
        if (popup?.closed) {
          clearInterval(interval);
          window.removeEventListener('message', handler);
          resolve(false);
        }
      }, 1000);
    });
  }

  // Called when user pastes the auth code manually (or after popup postMessage)
  async activateWithCode(authCode) {
    const result = await this.#apiCall('/oauth/exchange', {
      authCode,
      installationId:  this.#installationId,
      fingerprintHash: this.#fingerprint
    });

    this.#storeTokens(result.accessToken, result.refreshToken, result.expiresIn, result.tier, result.features);
    this.#tier     = result.tier;
    this.#features = result.features ?? [];
    this.#startHeartbeat();

    ui.notifications?.info(`VND Enhanced: Connected as ${result.tier} subscriber. Welcome!`);
  }

  // ── Release installation slot ───────────────────────────────────────────────

  async releaseInstallation() {
    try {
      await this.#apiCall('/license/release', { installationId: this.#installationId });
      this.#clearStoredTokens();
      this.#stopHeartbeat();
      ui.notifications?.info('VND Enhanced: Installation slot released.');
    } catch (e) {
      ui.notifications?.error(`VND Enhanced: Failed to release slot — ${e.message}`);
    }
  }

  // ── Internal: token storage ─────────────────────────────────────────────────

  #loadStoredTokens() {
    this.#accessToken  = localStorage.getItem(SK.accessToken);
    this.#refreshToken = localStorage.getItem(SK.refreshToken);
    this.#tokenExpiry  = Number.parseInt(localStorage.getItem(SK.tokenExpiry) ?? '0', 10);
    this.#features     = JSON.parse(localStorage.getItem(SK.features) ?? '[]');
    this.#tier         = localStorage.getItem(SK.tier) ?? 'none';
  }

  #storeTokens(at, rt, expiresIn, tier, features) {
    const expiry = Date.now() + expiresIn * 1000;
    this.#accessToken  = at;
    this.#refreshToken = rt;
    this.#tokenExpiry  = expiry;
    this.#tier         = tier;
    this.#features     = features ?? [];

    localStorage.setItem(SK.accessToken,  at);
    localStorage.setItem(SK.refreshToken, rt);
    localStorage.setItem(SK.tokenExpiry,  String(expiry));
    localStorage.setItem(SK.tier,         tier);
    localStorage.setItem(SK.features,     JSON.stringify(features ?? []));
  }

  #clearStoredTokens() {
    this.#accessToken  = null;
    this.#refreshToken = null;
    this.#tokenExpiry  = 0;
    this.#tier         = 'none';
    this.#features     = [];
    Object.values(SK).forEach(k => localStorage.removeItem(k));
  }

  #isAccessTokenValid() {
    return !!this.#accessToken && this.#tokenExpiry > Date.now() + 60_000; // 1-min buffer
  }

  #parseTierFromToken() {
    try {
      const payload = JSON.parse(atob(this.#accessToken.split('.')[1].replaceAll('-','+').replaceAll('_','/')));
      return payload.tier ?? 'none';
    } catch { return 'none'; }
  }

  #parseFeaturesFromToken() {
    try {
      const payload = JSON.parse(atob(this.#accessToken.split('.')[1].replaceAll('-','+').replaceAll('_','/')));
      return payload.features ?? [];
    } catch { return []; }
  }

  // ── Internal: installation ID ───────────────────────────────────────────────

  #getOrCreateInstallationId() {
    let iid = localStorage.getItem(SK.installationId);
    if (!iid) {
      iid = crypto.randomUUID();
      localStorage.setItem(SK.installationId, iid);
    }
    return iid;
  }

  // ── Internal: device fingerprint ────────────────────────────────────────────

  async #computeFingerprint() {
    const components = [
      game.world?.id ?? 'unknown',
      game.version ?? '',
      this.#installationId,
      navigator.language,
      navigator.hardwareConcurrency,
      screen.width, screen.height, screen.colorDepth,
      Intl.DateTimeFormat().resolvedOptions().timeZone,
      await this.#canvasFingerprint()
    ].join('|');

    const buf  = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(components));
    return btoa(String.fromCodePoint(...new Uint8Array(buf)));
  }

  async #canvasFingerprint() {
    try {
      const canvas = document.createElement('canvas');
      canvas.width = 200; canvas.height = 50;
      const ctx = canvas.getContext('2d');
      ctx.textBaseline = 'top';
      ctx.font = '14px Arial';
      ctx.fillStyle = '#f60';
      ctx.fillRect(125, 1, 62, 20);
      ctx.fillStyle = '#069';
      ctx.fillText('vnd-fp', 2, 15);
      ctx.fillStyle = 'rgba(102,204,0,0.7)';
      ctx.fillText('vnd-fp', 4, 17);
      return canvas.toDataURL().slice(-32);
    } catch { return 'no-canvas'; }
  }

  // ── Internal: refresh ───────────────────────────────────────────────────────

  async #doRefresh() {
    const result = await this.#apiCall('/token/refresh', {
      refreshToken:    this.#refreshToken,
      fingerprintHash: this.#fingerprint
    });
    this.#storeTokens(result.accessToken, result.refreshToken, result.expiresIn, result.tier, result.features);
  }

  // ── Internal: heartbeat ─────────────────────────────────────────────────────

  #startHeartbeat() {
    this.#stopHeartbeat();
    const INTERVAL = 15 * 60 * 1000; // 15 minutes
    this.#lastHeartbeat = Date.now();

    // First heartbeat after 1 minute (let Foundry finish loading)
    setTimeout(() => this.#doHeartbeat(), 60_000);
    this.#heartbeatTimer = setInterval(() => this.#doHeartbeat(), INTERVAL);
  }

  #stopHeartbeat() {
    if (this.#heartbeatTimer) {
      clearInterval(this.#heartbeatTimer);
      this.#heartbeatTimer = null;
    }
  }

  async #doHeartbeat() {
    try {
      const result = await this.#apiCall('/heartbeat', {
        installationId:  this.#installationId,
        fingerprintHash: this.#fingerprint
      });

      this.#storeTokens(result.accessToken, this.#refreshToken, result.expiresIn, result.tier, result.features);
      this.#lastHeartbeat = Date.now();
      this.#degraded = false;
    } catch {
      this.#handleHeartbeatFailure();
    }
  }

  #handleHeartbeatFailure() {
    const timeSinceLast = Date.now() - this.#lastHeartbeat;
    if (timeSinceLast > this.#gracePeriodMs) {
      if (!this.#degraded) {
        this.#degraded = true;
        // Notify GM silently — no intrusive UI for players
        if (game.user?.isGM) {
          ui.notifications?.warn('VND Enhanced: License server unreachable. Premium features suspended until reconnected.');
        }
      }
    }
  }

  // ── Internal: API call ──────────────────────────────────────────────────────

  async #apiCall(endpoint, body, method = 'POST') {
    const nonce     = crypto.randomUUID();
    const timestamp = Date.now();

    const init = {
      method,
      headers: {
        'Content-Type':       'application/json',
        'X-Installation-ID':  this.#installationId ?? '',
      }
    };

    if (this.#accessToken) {
      init.headers['Authorization'] = `Bearer ${this.#accessToken}`;
    }

    if (method === 'POST' && body !== null) {
      init.body = JSON.stringify({ ...body, nonce, timestamp });
    }

    const url  = `${API_BASE}${endpoint}`;
    const resp = await fetch(url, init);

    if (!resp.ok) {
      const err = await resp.json().catch(() => ({ error: 'Network error', code: 'NETWORK_ERROR' }));
      throw new LicenseError(err.error ?? 'Request failed', err.code ?? 'API_ERROR');
    }

    const data = await resp.json();

    // Verify response signature (anti-MITM)
    if (data.signature && data.payload && data.timestamp) {
      await this.#verifyResponseSignature(data);
      return data.payload;
    }

    return data;
  }

  async #verifyResponseSignature({ payload, signature, timestamp }) {
    // Timestamp window: ±30 seconds
    if (Math.abs(Date.now() - timestamp) > 30_000) {
      throw new LicenseError('Response timestamp out of window', 'REPLAY_DETECTED');
    }

    const key = await crypto.subtle.importKey(
      'raw',
      new TextEncoder().encode(RESPONSE_SIGN_SECRET),
      { name: 'HMAC', hash: 'SHA-256' },
      false,
      ['verify']
    );

    const message    = new TextEncoder().encode(JSON.stringify(payload) + timestamp);
    const sigBytes   = Uint8Array.from(atob(signature), c => c.codePointAt(0));
    const isValid    = await crypto.subtle.verify('HMAC', key, sigBytes, message);

    if (!isValid) {
      throw new LicenseError('Server response verification failed', 'SIGNATURE_INVALID');
    }
  }
}

// ── LicenseError ──────────────────────────────────────────────────────────────

export class LicenseError extends Error {
  constructor(message, code) {
    super(message);
    this.name = 'LicenseError';
    this.code = code;
  }
}

// ── License Prompt UI ─────────────────────────────────────────────────────────
// Shown to GM when the module is not licensed

export class VndLicenseUI {
  static show() {
    // Only show to GM
    if (!game.user?.isGM) return;

    const id = 'vnd-license-prompt';
    if (document.getElementById(id)) return;

    const el = document.createElement('div');
    el.id = id;
    el.style.cssText = `
      position:fixed; bottom:80px; right:20px; z-index:9999;
      background:#252540; border:1px solid #c89b3c44; border-radius:12px;
      padding:20px 24px; max-width:320px; box-shadow:0 8px 32px rgba(0,0,0,.6);
      font-family:system-ui,sans-serif; color:#e0d7c8;
    `;
    el.innerHTML = `
      <div style="display:flex;align-items:center;gap:10px;margin-bottom:12px">
        <span style="font-size:1.4rem">🔐</span>
        <strong style="color:#c89b3c;font-size:1rem">VND Enhanced</strong>
      </div>
      <p style="font-size:.85rem;color:#a09080;margin-bottom:16px;line-height:1.4">
        Connect your Patreon account to enable premium features.
      </p>
      <div style="display:flex;flex-direction:column;gap:8px">
        <button id="vnd-connect-btn" style="
          background:#c89b3c;color:#1a1a2e;border:none;border-radius:8px;
          padding:10px;font-size:.9rem;font-weight:700;cursor:pointer;width:100%
        ">Connect Patreon</button>
        <button id="vnd-code-btn" style="
          background:transparent;color:#a09080;border:1px solid #555;border-radius:8px;
          padding:8px;font-size:.8rem;cursor:pointer;width:100%
        ">I have an auth code</button>
        <button id="vnd-dismiss-btn" style="
          background:none;border:none;color:#605040;font-size:.75rem;cursor:pointer;
          text-align:right;padding:0
        ">Dismiss</button>
      </div>
    `;

    el.querySelector('#vnd-connect-btn').addEventListener('click', async () => {
      const btn = el.querySelector('#vnd-connect-btn');
      btn.textContent = 'Opening Patreon...';
      btn.disabled = true;
      try {
        const success = await VndLicenseClient.instance.startOAuth();
        if (success) el.remove();
        else { btn.textContent = 'Connect Patreon'; btn.disabled = false; }
      } catch (e) {
        btn.textContent = 'Connect Patreon'; btn.disabled = false;
        ui.notifications?.error(`VND Enhanced: ${e.message}`);
      }
    });

    el.querySelector('#vnd-code-btn').addEventListener('click', () => {
      VndLicenseUI.showCodeInput();
      el.remove();
    });

    el.querySelector('#vnd-dismiss-btn').addEventListener('click', () => el.remove());

    document.body.appendChild(el);
  }

  static showCodeInput() {
    new Dialog({
      title: 'VND Enhanced — Enter Auth Code',
      content: `
        <p style="margin-bottom:12px;font-size:.9rem">
          Paste the code shown after connecting your Patreon account.
        </p>
        <input id="vnd-auth-code-input" type="text"
          placeholder="Paste auth code here..."
          style="width:100%;padding:8px;border-radius:6px;border:1px solid #555;
                 background:#1a1a2e;color:#e0d7c8;font-family:monospace;font-size:.85rem"/>
      `,
      buttons: {
        activate: {
          label: '<i class="fas fa-key"></i> Activate',
          callback: async (html) => {
            const code = html.find('#vnd-auth-code-input').val().trim();
            if (!code) return;
            try {
              await VndLicenseClient.instance.activateWithCode(code);
            } catch (e) {
              ui.notifications?.error(`VND Enhanced: ${e.message}`);
            }
          }
        },
        cancel: { label: 'Cancel' }
      }
    }).render(true, { width: 420 });
  }
}
