-- ============================================================
-- VND Enhanced — License Schema for Supabase (PostgreSQL)
-- Run this in: Supabase Dashboard → SQL Editor
-- ============================================================

-- Enable UUID extension (already enabled in Supabase by default)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ── USERS ────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS vnd_users (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patreon_id          TEXT UNIQUE NOT NULL,
    email               TEXT,
    username            TEXT,
    tier                TEXT NOT NULL DEFAULT 'none',  -- 'none' | 'basic' | 'premium'
    tier_verified_at    TIMESTAMPTZ,
    -- Patreon tokens stored encrypted (pgcrypto) — key from env
    patreon_access      TEXT,
    patreon_refresh     TEXT,
    patreon_expires_at  TIMESTAMPTZ,
    status              TEXT NOT NULL DEFAULT 'active', -- 'active' | 'suspended' | 'banned'
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_vnd_users_patreon_id ON vnd_users(patreon_id);
CREATE INDEX IF NOT EXISTS idx_vnd_users_status     ON vnd_users(status);

-- ── INSTALLATIONS ─────────────────────────────────────────────────────────────
-- Each user can have up to N installations (default 2)
-- installation_id is a UUID generated by the client on first activation

CREATE TABLE IF NOT EXISTS vnd_installations (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    installation_id     TEXT UNIQUE NOT NULL,   -- UUID from client
    user_id             UUID NOT NULL REFERENCES vnd_users(id) ON DELETE CASCADE,
    slot_number         INTEGER NOT NULL,        -- 1 or 2

    -- What Foundry instance is this
    world_id            TEXT,                    -- game.world.id (slug)
    foundry_version     TEXT,

    -- Device fingerprint (hashed — never stored in clear)
    fingerprint_hash    TEXT NOT NULL,

    -- Status
    status              TEXT NOT NULL DEFAULT 'active', -- 'active' | 'revoked'
    revoked_at          TIMESTAMPTZ,
    revocation_reason   TEXT,

    -- Activity
    last_heartbeat      TIMESTAMPTZ,
    heartbeat_count     INTEGER NOT NULL DEFAULT 0,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(user_id, slot_number)
);

CREATE INDEX IF NOT EXISTS idx_vnd_inst_user_id        ON vnd_installations(user_id);
CREATE INDEX IF NOT EXISTS idx_vnd_inst_installation_id ON vnd_installations(installation_id);
CREATE INDEX IF NOT EXISTS idx_vnd_inst_status         ON vnd_installations(status);

-- ── REFRESH TOKENS ────────────────────────────────────────────────────────────
-- Opaque refresh tokens stored as SHA-256 hashes

CREATE TABLE IF NOT EXISTS vnd_refresh_tokens (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    token_hash          TEXT UNIQUE NOT NULL,       -- SHA-256 of the raw token
    user_id             UUID NOT NULL REFERENCES vnd_users(id) ON DELETE CASCADE,
    installation_id     UUID NOT NULL REFERENCES vnd_installations(id) ON DELETE CASCADE,
    fingerprint_hash    TEXT NOT NULL,

    -- Token family (for reuse detection)
    family_id           UUID NOT NULL DEFAULT uuid_generate_v4(),

    -- State
    is_revoked          BOOLEAN NOT NULL DEFAULT FALSE,
    revoked_at          TIMESTAMPTZ,
    revocation_reason   TEXT,
    replaced_by         UUID REFERENCES vnd_refresh_tokens(id),

    -- Usage
    last_used_at        TIMESTAMPTZ,
    use_count           INTEGER NOT NULL DEFAULT 0,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at          TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '30 days')
);

CREATE INDEX IF NOT EXISTS idx_vnd_rt_token_hash ON vnd_refresh_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_vnd_rt_user_id    ON vnd_refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_vnd_rt_family_id  ON vnd_refresh_tokens(family_id);
CREATE INDEX IF NOT EXISTS idx_vnd_rt_expires_at ON vnd_refresh_tokens(expires_at);

-- ── ANOMALIES ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS vnd_anomalies (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id         UUID REFERENCES vnd_users(id),
    installation_id UUID REFERENCES vnd_installations(id),
    anomaly_type    TEXT NOT NULL,
    severity        TEXT NOT NULL DEFAULT 'medium', -- 'low' | 'medium' | 'high' | 'critical'
    details         JSONB DEFAULT '{}',
    resolved        BOOLEAN DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_vnd_anomalies_user_id  ON vnd_anomalies(user_id);
CREATE INDEX IF NOT EXISTS idx_vnd_anomalies_severity ON vnd_anomalies(severity);

-- ── AUDIT LOG ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS vnd_audit (
    id              BIGSERIAL PRIMARY KEY,
    event_type      TEXT NOT NULL,
    user_id         UUID REFERENCES vnd_users(id),
    installation_id UUID REFERENCES vnd_installations(id),
    details         JSONB DEFAULT '{}',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_vnd_audit_user_id    ON vnd_audit(user_id);
CREATE INDEX IF NOT EXISTS idx_vnd_audit_event_type ON vnd_audit(event_type);
CREATE INDEX IF NOT EXISTS idx_vnd_audit_created_at ON vnd_audit(created_at);

-- ── UPDATED_AT TRIGGER ────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION vnd_set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_vnd_users_updated_at
    BEFORE UPDATE ON vnd_users
    FOR EACH ROW EXECUTE FUNCTION vnd_set_updated_at();

CREATE TRIGGER trg_vnd_inst_updated_at
    BEFORE UPDATE ON vnd_installations
    FOR EACH ROW EXECUTE FUNCTION vnd_set_updated_at();

-- ── ROW LEVEL SECURITY ────────────────────────────────────────────────────────
-- The service role key (used by the Worker) bypasses RLS.
-- Anon key is NOT used — the Worker always uses service role.

ALTER TABLE vnd_users         ENABLE ROW LEVEL SECURITY;
ALTER TABLE vnd_installations ENABLE ROW LEVEL SECURITY;
ALTER TABLE vnd_refresh_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE vnd_anomalies     ENABLE ROW LEVEL SECURITY;
ALTER TABLE vnd_audit         ENABLE ROW LEVEL SECURITY;

-- ── CLEANUP FUNCTION (run periodically via pg_cron or Supabase Edge Function) ──

CREATE OR REPLACE FUNCTION vnd_cleanup_expired()
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    -- Remove expired refresh tokens older than 7 days
    DELETE FROM vnd_refresh_tokens
    WHERE expires_at < NOW() - INTERVAL '7 days';

    -- Remove old audit entries (keep 90 days)
    DELETE FROM vnd_audit
    WHERE created_at < NOW() - INTERVAL '90 days';
END;
$$;
